acceleration:
  look: 0.03
  takeoff:
    vertical: 0.5
    look: 0.5

takeoff:
  glide_millis: 1000
  tap_millis: 500

max_velocity: 2.0

gauge_debounce_millis: 1000

# Parameters to World.spawnParticle()
exhaust:
  effect: FIREWORKS_SPARK
  offset: 0.3
  speed: 0.01
  count: 5
  sound: ENTITY_ELDER_GUARDIAN_AMBIENT
  volume: 4.0

broken:
  sound: BLOCK_FURNACE_FIRE_CRACKLE
  volume: 3.0
  glide: true
  glide_fall_reduction: 2.0

altimeter:
  enabled: true
  ceiling: 300.0
  colours:
    '100': RED
    '200': BLUE
    '256': WHITE
    '300': PINK

speedometer:
  enabled: true
  max: 2.0
  colour: BLUE

wingometer:
  enabled: true
  colours:
    '10': RED
    '30': YELLOW
    '101': GREEN

pitchmeter:
  enabled: true
  min: -90.0
  max: 90.0
  colours:
    '-20': RED
    '-10': YELLOW
    '11': GREEN
    '21': YELLOW
    '91': RED

vacuum:
  enabled: true
  altitude: 300.0
  damage: 1.0

tnt_throw_speed: 1.0
